name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Spécifie la version de Python que tu souhaites utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qrcode[pil] pytest pyvirtualdisplay

    - name: Run tests with virtual display
      run: |
        # Démarre l'affichage virtuel
        python -c "from pyvirtualdisplay import Display; Display().start()"
        # Exécute les tests
        pytest QRCodeGeneratorApp/test_main.py  # Ajuste le chemin si nécessaire
